"""
Report generation: JSON (machine readable), Markdown (disclosure ready)
and a self-contained HTML briefing.

Reports describe *identified weaknesses with static evidence*. They are
written to be attached to a coordinated disclosure, and deliberately never
contain an exploit chain or runnable payload.
"""

from __future__ import annotations

import html
import json
from datetime import datetime, timezone
from pathlib import Path

from .core import Engagement, Finding, ScanResult, Severity, TOOL_NAME, __version__


# --------------------------------------------------------------------------
# JSON
# --------------------------------------------------------------------------
def write_json(result: ScanResult, engagement: Engagement, out: Path) -> Path:
    out = Path(out)
    payload = result.to_dict()
    payload["engagement"] = engagement.to_dict()
    payload["generated_utc"] = datetime.now(timezone.utc).isoformat(timespec="seconds")
    out.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    return out


# --------------------------------------------------------------------------
# Markdown - structured for a vulnerability disclosure submission
# --------------------------------------------------------------------------
def write_markdown(result: ScanResult, engagement: Engagement, out: Path) -> Path:
    out = Path(out)
    counts = result.counts()
    lines: list[str] = []
    a = lines.append

    a(f"# Security Assessment - {engagement.target}")
    a("")
    a(f"**Tool:** {TOOL_NAME} v{__version__}  ")
    a(f"**Generated:** {datetime.now(timezone.utc).isoformat(timespec='seconds')} UTC  ")
    a(f"**Operator:** {html.escape(engagement.operator) or 'unspecified'}  ")
    if engagement.ticket:
        a(f"**Reference / ticket:** {engagement.ticket}  ")
    a(f"**Overall posture:** {result.posture()} (risk score {result.risk_score()}/100)")
    a("")

    a("## 1. Scope and authorisation")
    a("")
    a("> " + (engagement.scope_notes or
              "Assessment of a locally installed Cfx.re / FiveM (FXServer) "
              "application tree owned or controlled by the operator."))
    a("")
    a("**Attestation of authorisation:**")
    a("")
    a("> " + (Engagement.attestation_text if engagement.authorized
              else "_No attestation recorded._"))
    a("")
    a("**Method boundary.** This assessment is strictly passive and read-only. "
      "No process injection, memory manipulation, code execution on a target, "
      "credential attack, denial-of-service, or exploitation of a third-party "
      "system was performed at any point. Findings are derived from static "
      "analysis of files on disk and from unauthenticated reads of the "
      "operator's own loopback endpoints.")
    a("")

    a("## 2. Summary")
    a("")
    a("| Severity | Count |")
    a("|---|---|")
    for sev in reversed(list(Severity)):
        a(f"| {sev.label} | {counts[sev.label]} |")
    a(f"| **Total** | **{len(result.findings)}** |")
    a("")

    inv = result.metadata.get("inventory", {})
    if inv:
        a("### Target inventory")
        a("")
        a(f"- Root: `{inv.get('root', 'n/a')}`")
        a(f"- Files analysed: {inv.get('file_count', 0):,}")
        a(f"- Total size: {inv.get('total_bytes', 0):,} bytes")
        if inv.get("by_extension"):
            top = ", ".join(f"{k} ({v})" for k, v in list(inv["by_extension"].items())[:10])
            a(f"- Most common extensions: {top}")
        a("")

    a("## 3. Findings")
    a("")
    if not result.findings:
        a("_No findings above the configured threshold._")
        a("")
    else:
        for cat, findings in result.by_category().items():
            a(f"### {cat}")
            a("")
            for f in findings:
                a(_md_finding(f))
    a("## 4. Recommended remediation order")
    a("")
    order = sorted(result.findings, key=lambda f: -int(f.severity))
    seen: set[str] = set()
    n = 0
    for f in order:
        if f.rule_id in seen:
            continue
        seen.add(f.rule_id)
        n += 1
        a(f"{n}. **[{f.severity.label}] {f.title}** - {f.remediation}")
    a("")
    a("---")
    a("")
    a("_Generated by " + TOOL_NAME + " v" + __version__ +
      ". Evidence values are redacted so this document can be shared safely._")

    out.write_text("\n".join(lines), encoding="utf-8")
    return out


def _md_finding(f: Finding) -> str:
    loc = f.location
    parts = [
        f"#### {f.rule_id} - {f.title}",
        "",
        f"- **Severity:** {f.severity.label}",
        f"- **Category:** {f.category}",
        f"- **Confidence:** {f.confidence.label}",
    ]
    if f.cwe:
        parts.append(f"- **Weakness:** {f.cwe}")
    parts.append(f"- **Location:** `{loc}`")
    if f.evidence:
        parts.append(f"- **Evidence:** `{f.evidence}`")
    parts += [
        "",
        f"**Description.** {f.description}",
        "",
        f"**Impact.** {f.impact}",
        "",
        f"**Remediation.** {f.remediation}",
    ]
    if f.references:
        parts += ["", "**References.**"]
        parts += [f"- {r}" for r in f.references]
    if f.tags:
        parts += ["", f"*Tags: {', '.join(f.tags)}*"]
    parts += [""]
    return "\n".join(parts)


# --------------------------------------------------------------------------
# HTML
# --------------------------------------------------------------------------
CSS = """
:root{
  --bg:#070b12; --panel:#0e1420; --panel2:#131c2b; --line:#1e2b3f;
  --fg:#c8d6e5; --dim:#6b7f96; --acc:#00e5ff; --acc2:#7c5cff; --warn:#ffb020;
  --crit:#ff3b5c; --high:#ff7a45; --med:#ffd166; --low:#2ee6a8; --info:#5b6b7c;
}
*{box-sizing:border-box}
body{margin:0;background:
  radial-gradient(1200px 600px at 15% -10%, #12203a 0%, transparent 60%),
  radial-gradient(900px 500px at 100% 0%, #1a1030 0%, transparent 55%),
  var(--bg);
  color:var(--fg);font:14px/1.6 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}
.wrap{max-width:1180px;margin:0 auto;padding:32px 24px 80px}
header{border:1px solid var(--line);background:linear-gradient(135deg,#0d1626,#131029);
  border-radius:14px;padding:26px 28px;position:relative;overflow:hidden}
header::after{content:"";position:absolute;inset:0;
  background:repeating-linear-gradient(0deg,transparent 0 3px,rgba(0,229,255,.03) 3px 4px);
  pointer-events:none}
h1{margin:0 0 6px;font-size:24px;letter-spacing:.5px;color:#fff}
h1 span{color:var(--acc)}
.sub{color:var(--dim);font-size:12.5px}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px;margin:22px 0}
.card{border:1px solid var(--line);background:var(--panel);border-radius:12px;padding:14px 16px}
.card .n{font-size:26px;font-weight:700;line-height:1.1}
.card .l{font-size:11px;letter-spacing:1.4px;color:var(--dim);text-transform:uppercase}
.meter{height:8px;border-radius:99px;background:#16202f;overflow:hidden;margin-top:10px}
.meter i{display:block;height:100%;background:linear-gradient(90deg,var(--acc),var(--crit))}
h2{font-size:15px;letter-spacing:1.8px;text-transform:uppercase;color:var(--acc);
   margin:34px 0 14px;border-bottom:1px solid var(--line);padding-bottom:8px}
table{width:100%;border-collapse:collapse;font-size:13px}
th,td{text-align:left;padding:9px 10px;border-bottom:1px solid var(--line);vertical-align:top}
th{color:var(--dim);font-weight:600;font-size:11px;letter-spacing:1.2px;text-transform:uppercase}
.sev{display:inline-block;padding:2px 9px;border-radius:99px;font-size:11px;font-weight:700;
     letter-spacing:.6px;color:#07101a}
.sev.CRITICAL{background:var(--crit);color:#fff}
.sev.HIGH{background:var(--high)}
.sev.MEDIUM{background:var(--med)}
.sev.LOW{background:var(--low)}
.sev.INFO{background:var(--info);color:#fff}
details{border:1px solid var(--line);background:var(--panel);border-radius:10px;
        margin:8px 0;overflow:hidden}
summary{cursor:pointer;padding:11px 14px;background:var(--panel2);font-weight:600;
        list-style:none;display:flex;gap:10px;align-items:center;flex-wrap:wrap}
summary::-webkit-details-marker{display:none}
summary::before{content:"▸";color:var(--acc)}
details[open] summary::before{content:"▾"}
.loc{color:var(--dim);font-size:12px;font-weight:400;word-break:break-all}
.body{padding:14px 16px;border-top:1px solid var(--line)}
.body p{margin:0 0 10px}
.body b{color:var(--acc)}
code{background:#0a1220;border:1px solid var(--line);border-radius:5px;
     padding:1px 6px;color:#9fe8ff;font-size:12.5px;word-break:break-all}
pre{background:#0a1220;border:1px solid var(--line);border-radius:8px;
    padding:10px 12px;overflow-x:auto;color:#9fe8ff;font-size:12.5px;margin:0 0 10px}
.tag{display:inline-block;background:#16233a;border:1px solid var(--line);
     color:var(--dim);border-radius:99px;padding:1px 8px;font-size:11px;margin-right:5px}
.note{border-left:3px solid var(--warn);background:#19150566;padding:12px 16px;
      border-radius:0 8px 8px 0;margin:14px 0;color:#e9d9b4;font-size:13px}
.ok{border-left:3px solid var(--low);background:#04170f66;padding:12px 16px;
    border-radius:0 8px 8px 0;margin:14px 0;font-size:13px}
footer{margin-top:40px;color:var(--dim);font-size:11.5px;border-top:1px solid var(--line);
       padding-top:16px}
"""


def write_html(result: ScanResult, engagement: Engagement, out: Path) -> Path:
    out = Path(out)
    counts = result.counts()
    e = html.escape
    parts: list[str] = []
    a = parts.append

    a("<!doctype html><html lang='en'><head><meta charset='utf-8'>")
    a("<meta name='viewport' content='width=device-width,initial-scale=1'>")
    a(f"<title>{TOOL_NAME} - Security Assessment</title><style>{CSS}</style></head><body><div class='wrap'>")

    a("<header>")
    a(f"<h1><span>{TOOL_NAME}</span> :: SECURITY ASSESSMENT</h1>")
    a(f"<div class='sub'>TARGET: {e(str(engagement.target))}</div>")
    a(f"<div class='sub'>OPERATOR: {e(engagement.operator or 'unspecified')}"
      f" &nbsp;|&nbsp; GENERATED: "
      f"{datetime.now(timezone.utc).isoformat(timespec='seconds')} UTC"
      f" &nbsp;|&nbsp; ENGINE v{__version__}</div>")
    score = result.risk_score()
    a(f"<div class='sub' style='margin-top:8px'>POSTURE: "
      f"<b style='color:var(--warn)'>{e(result.posture())}</b> "
      f"({score}/100)</div>")
    a("<div class='meter'><i style='width:%d%%'></i></div>" % max(2, score))
    a("</header>")

    a("<div class='grid'>")
    for sev, color in (("CRITICAL", "var(--crit)"), ("HIGH", "var(--high)"),
                       ("MEDIUM", "var(--med)"), ("LOW", "var(--low)"),
                       ("INFO", "var(--info)")):
        a("<div class='card'>")
        a(f"<div class='n' style='color:{color}'>{counts[sev]}</div>")
        a(f"<div class='l'>{sev}</div></div>")
    a("</div>")

    a("<h2>Scope &amp; Authorisation</h2>")
    a("<div class='ok'><b>Authorised:</b> "
      + (e(Engagement.attestation_text) if engagement.authorized
         else "no attestation recorded")
      + "</div>")
    if engagement.scope_notes:
        a(f"<div class='note'><b>Scope:</b> {e(engagement.scope_notes)}</div>")
    a("<div class='note'><b>Method boundary:</b> passive and read-only. "
      "No process injection, memory manipulation, exploitation, credential "
      "attack or denial of service was performed. Findings derive from static "
      "analysis of files on disk and unauthenticated reads of the operator's "
      "own loopback endpoints. Evidence is redacted.</div>")

    inv = result.metadata.get("inventory", {})
    if inv:
        a("<h2>Target Inventory</h2><table>")
        a("<tr><th>Root</th><td><code>" + e(str(inv.get("root", ""))) + "</code></td></tr>")
        a(f"<tr><th>Files analysed</th><td>{inv.get('file_count', 0):,}</td></tr>")
        a(f"<tr><th>Total size</th><td>{inv.get('total_bytes', 0):,} bytes</td></tr>")
        if inv.get("by_extension"):
            top = ", ".join(f"{k} &times;{v}" for k, v in list(inv["by_extension"].items())[:12])
            a(f"<tr><th>Top extensions</th><td>{e(top)}</td></tr>")
        a("</table>")

    a(f"<h2>Findings ({len(result.findings)})</h2>")
    if not result.findings:
        a("<div class='ok'>No findings above the configured threshold.</div>")
    for cat, findings in result.by_category().items():
        a(f"<h3 style='color:var(--fg);font-size:13px;letter-spacing:1px'>"
          f"{e(cat)} &mdash; {len(findings)}</h3>")
        for f in findings:
            a("<details><summary>")
            a(f"<span class='sev {f.severity.label}'>{f.severity.label}</span>")
            a(f"<span>{e(f.rule_id)}</span>")
            a(f"<span>{e(f.title)}</span>")
            a(f"<span class='loc'>{e(f.location)}</span>")
            a("</summary><div class='body'>")
            if f.cwe:
                a(f"<p><b>Weakness:</b> {e(f.cwe)} &nbsp; "
                  f"<b>Confidence:</b> {f.confidence.label}</p>")
            if f.evidence:
                a(f"<p><b>Evidence:</b></p><pre>{e(f.evidence)}</pre>")
            a(f"<p><b>Description.</b> {e(f.description)}</p>")
            a(f"<p><b>Impact.</b> {e(f.impact)}</p>")
            a(f"<p><b>Remediation.</b> {e(f.remediation)}</p>")
            if f.references:
                a("<p><b>References.</b><br>" +
                  "<br>".join(e(r) for r in f.references) + "</p>")
            if f.tags:
                a("<p>" + "".join(f"<span class='tag'>{e(t)}</span>"
                                  for t in f.tags) + "</p>")
            a("</div></details>")

    a("<footer>")
    a(f"{TOOL_NAME} v{__version__} &mdash; authorized, read-only assessment. "
      "This document contains no exploit code and is safe to attach to a "
      "coordinated disclosure.</footer>")
    a("</div></body></html>")

    out.write_text("\n".join(parts), encoding="utf-8")
    return out


# --------------------------------------------------------------------------
# Facade
# --------------------------------------------------------------------------
def write_reports(result: ScanResult, engagement: Engagement,
                  outdir: Path, formats: list[str]) -> dict[str, Path]:
    outdir = Path(outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    written: dict[str, Path] = {}
    if "json" in formats or "all" in formats:
        written["json"] = write_json(result, engagement, outdir / "fivem-audit.json")
    if "md" in formats or "all" in formats:
        written["md"] = write_markdown(result, engagement, outdir / "fivem-audit.md")
    if "html" in formats or "all" in formats:
        written["html"] = write_html(result, engagement, outdir / "fivem-audit.html")
    return written


# Attach the attestation text as a class attribute for reuse in templates.
Engagement.attestation_text = (
    "I confirm that I own this target or hold written authorization from its "
    "owner to perform a read-only security assessment, and that this scan is "
    "conducted within an agreed scope and window."
)
